site_name: Orkid MIDP
theme:
  logo: assets/logo.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: indigo

nav:
  - MIDP: index.md
  - Getting Started: getting-started.md
  # - Overview: overview.md
  # - Document Uploading: uploads.md
  - API Reference: api-reference.md
  - FAQ: faq.md

  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details


plugins:
  - search
  - swagger-ui-tag

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/orkidio


copyright: |
  &copy; 2024 <a href="http://www.orkid.io"  target="_blank" rel="noopener">Orkid.io</a>